DROP PROCEDURE IF EXISTS MODIFY_TYPE_OF_DESCRIPTION_COLUMN;
CREATE PROCEDURE MODIFY_TYPE_OF_DESCRIPTION_COLUMN()
    language plpgsql
as $$
BEGIN
ALTER TABLE product
ALTER COLUMN description TYPE VARCHAR;
END $$;
CALL MODIFY_TYPE_OF_DESCRIPTION_COLUMN();
DROP PROCEDURE MODIFY_TYPE_OF_DESCRIPTION_COLUMN;